SSO experimental sample cleanup
microsoft/BotBuilder-Samples pull request #3052
Opened 2021-01-27 19:38 UTC by gabog

Cleaned up and simplified the SSO experimental sample.
Improved dialog flow
Removed unnecessary overload.
Align sample structure and code with SkillDialog sample

2021-01-27 21:18 UTC, gabog commented
Hi @JonathanFingold, this will probably impact some of the docs we have, can you also take a look?

Thanks

2021-01-28 17:45 UTC, JonathanFingold commented
> Hi @JonathanFingold, this will probably impact some of the docs we have, can you also take a look?

@gabog -- Thanks, I'll take a look.

2021-01-28 19:09 UTC, JonathanFingold reviewed
A bunch of copy edit requests in comments and strings.

2021-01-28 19:09 UTC, JonathanFingold commented on experimental/sso-with-skills/SkillBot/Dialogs/SsoSkillDialog.cs
> +                    // This should never be hit since the previous prompt validates the choice
```suggestion
                    // This should never be hit since the previous prompt validates the choice.
```

2021-01-28 19:09 UTC, JonathanFingold commented on experimental/sso-with-skills/SkillBot/Dialogs/SsoSkillDialog.cs
> +            // Restart the dialog (we will exit when the user says end)
```suggestion
            // Restart the dialog (we will exit when the user says "end").
```

2021-01-28 19:09 UTC, JonathanFingold commented on experimental/sso-with-skills/SkillBot/SsoSkillAdapterWithErrorHandler.cs
> +    /// In addition to handle different skill specific skill logic, this adapter also overrides
```suggestion
    /// In addition to handling different skill specific skill logic, this adapter also overrides
```

2021-01-28 19:09 UTC, JonathanFingold commented on experimental/sso-with-skills/SkillBot/SsoSkillAdapterWithErrorHandler.cs
> +    /// This prepares the bot to receive the Activity send by the TokenExchangeSkillHandler.
```suggestion
    /// This prepares the bot to receive the activity send by the TokenExchangeSkillHandler.
```

2021-01-28 19:09 UTC, JonathanFingold commented on experimental/sso-with-skills/SkillBot/SsoSkillAdapterWithErrorHandler.cs
> +        // This overrides ensures that the conversation state is saved when the outgoing activity contains an OAuthPrompt
```suggestion
        // This overrides ensures that the conversation state is saved when the outgoing activity contains an OAuthPrompt.
```

2021-01-28 19:09 UTC, JonathanFingold commented on experimental/sso-with-skills/SkillBot/SsoSkillAdapterWithErrorHandler.cs
> +                    // this ensure the skill state is consistent if the SSO handler sends and invoke in.
```suggestion
                    // Save any state changes that might have occurred during the turn before sending anything.
                    // This ensures the skill state is consistent if the SSO handler sends in an invoke activity.
```

2021-01-28 19:09 UTC, JonathanFingold commented on experimental/sso-with-skills/SkillBot/SsoSkillAdapterWithErrorHandler.cs
> +                // ConversationState should be thought of as similar to "cookie-state" for a Web page.
```suggestion
                // ConversationState should be thought of as similar to "cookie-state" for a web page.
```

2021-01-28 19:09 UTC, JonathanFingold commented on experimental/sso-with-skills/SkillBot/SsoSkillAdapterWithErrorHandler.cs
> +                _logger.LogError(ex, $"Exception caught on attempting to Delete ConversationState : {ex}");
```suggestion
                _logger.LogError(ex, $"Exception caught on attempting to delete ConversationState : {ex}");
```

2021-01-28 19:09 UTC, JonathanFingold commented on experimental/sso-with-skills/SkillBot/Startup.cs
>              // Configure credentials
```suggestion
            // Configure credentials.
```

2021-01-28 20:13 UTC, mdrichardson commented
Notes to all:

I just pushed the JS port; @gabog and I thought it made sense to keep them under a single PR. Note: the whole .NET bot is nested under an additional folder, `chsarp_dotnetcore`.

@JonathanFingold I implemented the changes to the .NET parts you mentioned and also made the same changes in the JS port, where applicable. It could use review as well, of course. I also updated the READMEs for both that could use your gooder word stuff.

2021-01-29 20:17 UTC, JonathanFingold reviewed
A bunch of copy edits for you, some optional.

2021-01-29 20:17 UTC, JonathanFingold commented on experimental/sso-with-skills/javascript_nodejs/README.md
> +- Install npm modules and start the bot
```suggestion
- Install npm modules and start the bot.
```

2021-01-29 20:17 UTC, JonathanFingold commented on experimental/sso-with-skills/javascript_nodejs/README.md
> +- Open a **second** terminal window and navigate to `samples\javascript_nodejs\82.sso-with-skills\rootBot`
```suggestion
- Open a *second* terminal window and navigate to `samples\javascript_nodejs\82.sso-with-skills\rootBot`.
```

2021-01-29 20:17 UTC, JonathanFingold commented on experimental/sso-with-skills/javascript_nodejs/README.md
> +- Install npm modules and start the bot
```suggestion
- Install npm modules and start the bot.
```

2021-01-29 20:17 UTC, JonathanFingold commented on experimental/sso-with-skills/javascript_nodejs/README.md
> +[Bot Framework Emulator](https://github.com/microsoft/botframework-emulator) is a desktop application that allows bot developers to test and debug their bots on localhost or running remotely through
We've (the docs team) have recently agreed to use "the" with the Emulator, but it's up to you, as long as you're consistent.
```suggestion
## Testing the bot using the Bot Framework Emulator

The [Bot Framework Emulator](https://github.com/microsoft/botframework-emulator) is a desktop application that allows bot developers to test and debug their bots on localhost or running remotely through a tunnel.
```

2021-01-29 20:17 UTC, JonathanFingold commented on experimental/sso-with-skills/javascript_nodejs/README.md
> +- Follow the prompts to initiate the token exchange between the `SkillBot` and `RootBot`, resulting in a valid token displayed
```suggestion
### Connect to the bot using the Bot Framework Emulator

- Launch the Bot Framework Emulator.
- Select **File** > **Open Bot**.
- Enter a Bot URL of `http://localhost:3978/api/messages`, and fill in the **Microsoft App ID** and **Microsoft App password** for the root bot.
- Select **Connect**.
- Follow the prompts to initiate the token exchange between the skill bot and root bot. The bot will display a valid token.
```
The MS writing style for docs for UI interactions is to use bold for UI elements that are labeled (or have hover text), ">" to chain sub-menus, and to use "select" (for _clicking_ a button or choosing a menu item). Again, I'll leave it up to you if you want to follow the same guidelines as for the doc team.

2021-10-22 01:03 UTC, BruceHaley requested changes
These deployment templates are out of date. The Microsoft.BotService/botServices resource kind "bot" is no longer supported, and needs to be updated to "azurebot".

See line 160 in experimental/sso-with-skills/csharp_dotnetcore/RootBot/DeploymentTemplates/template-with-new-rg.json

Also I would change the apiVersion to the newer date as indicated.

Outdated:
                            "apiVersion": "2017-12-01",
                            "type": "Microsoft.BotService/botServices",
                            "name": "[parameters('botId')]",
                            "location": "global",
                            "kind": "bot",
Current:
                            "apiVersion": "2021-03-01",
                            "type": "Microsoft.BotService/botServices",
                            "name": "[parameters('botId')]",
                            "location": "global",
                            "kind": "azurebot",

Examples of correctly formed templates are:
samples\csharp_dotnetcore\02.echo-bot\DeploymentTemplates\template-with-new-rg.json
samples\csharp_dotnetcore\02.echo-bot\DeploymentTemplates\template-with-preexisting-rg.json

2022-04-21 16:14 UTC, gabog commented
This is a stale PR, closing

2022-04-21 16:14 UTC, closed without merging