Sample for testing Teams Tabs
microsoft/BotBuilder-Samples pull request #3087
Opened 2021-02-17 08:19 UTC by axelsrz

Fixes: Our lack of this sample in python.

2021-02-17 15:52 UTC, bhargavimohan commented
I tried to run this after installing the SDK from `https://github.com/microsoft/botbuilder-python/tree/axsuarez/teams-ac-tabs` 

but i seem to get this error

`ImportError: cannot import name 'TabResponse'`

TabResponse also does not seem to be defined in botbuilder-schema

2021-02-18 19:41 UTC, EricDahlvang commented
Hi @bhargavimohan 

We've fixed a bug related to this:
https://github.com/microsoft/botbuilder-python/pull/1538

As well as some updates to the sample:
https://github.com/microsoft/BotBuilder-Samples/pull/3087/commits/d42d9370e4115ec50676ece0403698eaa70e137d

2021-02-19 19:32 UTC, mdrichardson requested changes
Just a couple nit-picky things. My review also assumes this works--I can't test it, myself, due to not being able to get on the right Teams ring.

2021-02-19 19:32 UTC, mdrichardson commented on experimental/teams-tabs/python/README.md
> +# Teams Task Module
This should reflect Teams Tabs. [see here](https://github.com/mdrichardson/BotBuilder-Samples/blob/teamsTabs/experimental/teams-tabs/javascript_nodejs/README.md)

2021-02-19 19:32 UTC, mdrichardson commented on experimental/teams-tabs/python/bots/teams_adaptive_card_tabs_bot.py
> +        self.__base_url = config.BASE_URL
I believe this is unused and can be omitted.

2021-02-22 14:58 UTC, bhargavimohan commented
Hi Eric,

Thank you for your email. I am looking for an example for configurable tabs
in python. Can you please provide me with an example sample.

I am trying to design a tab that renders the content from my ngrok
endpoint. I tried to add a configurable tab but i get the following error
marked in a rectangle. Or can you hint me with what I am missing? It would
be of great help

[image: image.png]

Thank you
Bhargavi Mohan


On Thu, 18 Feb 2021 at 20:41, Eric Dahlvang <notifications@github.com>
wrote:

> Hi @bhargavimohan <https://github.com/bhargavimohan>
>
> We've fixed a bug related to this:
> microsoft/botbuilder-python#1538
> <https://github.com/microsoft/botbuilder-python/pull/1538>
>
> As well as some updates to the sample:
> d42d937
> <https://github.com/microsoft/BotBuilder-Samples/commit/d42d9370e4115ec50676ece0403698eaa70e137d>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/microsoft/BotBuilder-Samples/pull/3087#issuecomment-781589198>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKQHAOCMDKU6H2SDCX2GAETS7VUQNANCNFSM4XX4X44Q>
> .
>

2021-02-22 17:52 UTC, EricDahlvang commented
I'm sorry @bhargavimohan but, this is a Draft Pull Request into the BotBuilder-Samples repository.  Not a valid location for question/answers.  Please direct questions to Stack Overflow.

I'm not sure about Teams 'configurable tabs'.  This PR is related to a new feature: Adaptive Card Tabs.

2021-02-22 18:03 UTC, bhargavimohan commented
Hey!

Thanks for your quick response. I understand that.

I figured out about configuration tabs! Thanks anyway :)




On Mon, 22 Feb 2021 at 18:52, Eric Dahlvang <notifications@github.com>
wrote:

> I'm sorry @bhargavimohan <https://github.com/bhargavimohan> but, this is
> a Draft Pull Request into the BotBuilder-Samples repository. Not a valid
> location for question/answers. Please direct questions to Stack Overflow.
>
> I'm not sure about Teams 'configurable tabs'. This PR is related to a new
> feature: Adaptive Card Tabs.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/microsoft/BotBuilder-Samples/pull/3087#issuecomment-783554735>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKQHAOAB7R4CAL6DM6GDD4TTAKKXJANCNFSM4XX4X44Q>
> .
>

2021-02-22 18:18 UTC, EricDahlvang commented
@bhargavimohan  good to hear :)

2021-11-11 19:59 UTC, BruceHaley requested changes

2021-11-11 19:59 UTC, BruceHaley commented on experimental/teams-tabs/python/deploymentTemplates/template-with-new-rg.json
> +                            "kind": "bot",
"kind": "bot" is out of date, no longer supported. See my earlier comment.

2021-11-11 19:59 UTC, BruceHaley commented on experimental/teams-tabs/python/deploymentTemplates/template-with-preexisting-rg.json
> +        "kind": "bot",
"kind": "bot" is out of date, no longer supported. See my earlier comment.

2022-04-21 16:14 UTC, EricDahlvang commented
Closing, we've decided to not include this.

2022-04-21 16:14 UTC, closed without merging